### ISSUE TITLE
Making data.cpa on Linux + character slows down in battles due to X11 key repeat misinterpretation in Allegro

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#5] opened 2015-08-12 06:25 UTC
Hi there,

I've tried to use tools/mkcpa-linux.sh but I had issues with the packtiles2.exe not existing; I suppose it's built by the CMake scripts that I haven't tried to use too much right now as they are tailor-made for your dev environment, but to make things simpler I added a small instructions to build it directly from the bash script, plus various ease of use improvements: https://github.com/akien-mga/crystal-picnic/commit/c74927d35e149fdd7f3b248bb970f6faff756398

It seems to work, though my archive is smaller than the one you provide in the 1.6 binary tarball:
```
total 19548
-rw-r--r-- 1 akien akien  5466189 août  12 08:15 data.cpa
-rw-r--r-- 1 akien akien 14541185 août  12 08:15 data.cpa.uncompressed
```

And it does not seem to work if I replace the data.cpa from the 1.6 release with mine:
```
[LOG] Loaded Animation_Set descriptor info.xml.
[LOG] Animation set misc_graphics/speech_window loaded.
[LOG] Loaded Animation_Set descriptor info.xml.
[LOG] Animation set misc_graphics/speech_arrow loaded.
CrystalPicnic: /home/trent/code/allegro/src/file.c:150: al_ftell: Assertion `f' failed.
```

I guess building packtiles2 with a gcc one-liner is not enough to get the whole thing working?

**Comment by trentg** [comment] 2015-08-12 06:31
See data/Notice.txt, you're missing some files. If you're going to package for Linux you'll need to find replacements.

**Comment by akien-mga** [comment] 2015-08-12 06:35
Ah right, thanks. I do plan to package for Linux and will search for replacements, though I'm not working on it right now. For now I'm more trying to test my WIP French translation in-game ;)
Can I extract those files from the binary package, or could you send them to me for development purpose?

**Comment by trentg** [comment] 2015-08-12 06:43
I'm not at liberty to distribute those files to anyone outside the official packages. The best way to test a translation is to build the game with TRANSLATION_BUILD defined (see engine.cpp), then the game looks for Translation.utf8 in the CWD and also reloads said file when you press F1.

**Comment by akien-mga** [comment] 2015-08-12 06:52
Thanks! I guess I'll have to dig into the CMake scripts sooner than I anticipated ;)
I'll also see if I can use some placeholder fonts and SoundFonts.

**Comment by akien-mga** [comment] 2015-08-12 08:01
As I suspect it will take me some time to setup the right build environment with bassmidi, etc., would you mind providing me with a build of the game with TRANSLATION_BUILD defined?

**Comment by trentg** [comment] 2015-08-12 08:19
Not a problem.

**Comment by akien-mga** [comment] 2015-08-14 16:51
Just so you know, the save function seems broken with the translation-enabled build that you gave me. Is it expected, or might it hint at a bigger problem in the 1.7 version? I've tried saving both new games and after loading saved games from 1.6, and in both cases it saves "Save successful" but no data is written.

I've checked and I have write access to ```~/.config/Nooskewl/Crystal Picnic```

**Comment by trentg** [comment] 2015-08-14 16:55
Now that you mention it, I think I know what the problem is, but it only affects the translation build. I think the user resource directory is being changed so that the translation can be loaded. Not 100% though.

**Comment by trentg** [comment] 2015-08-14 16:56
Have you tried the official 1.7 builds? Nothing has changed since those that would have any effect on this issue.

**Comment by trentg** [comment] 2015-08-14 17:18
Hold on, happens to me too without the translation build. Investigating.

**Comment by trentg** [comment] 2015-08-14 17:28
Git blame shows a commit on 2015-07-30 that causes this... don't know what I was thinking. Thanks for finding this!!!

**Comment by trentg** [comment] 2015-08-14 17:29
And I'm sorry about your game >_<

**Comment by akien-mga** [comment] 2015-08-14 17:30
> And I'm sorry about your game >_<

No problem, I did not lose any progress, I was just checking my translations live in River Town. Now I've played a bit further with 1.6 :)

**Comment by trentg** [comment] 2015-08-14 17:36
Any other issues? I'm about to release 1.7 on Windows, and then patch everything else for this bug. >_<

**Comment by akien-mga** [comment] 2015-08-14 17:43
Nothing specific comes to mind, just make sure that b03dc11c does not cause issues. With the translation build locally, after I removed this string from my translations, I had a segfault on start. But maybe that's just because the string is present in English.utf8 and couldn't be matched in TRANSLATION.utf8?

**Comment by trentg** [comment] 2015-08-14 17:44
Thanks for the heads up. How's the translation coming?

**Comment by akien-mga** [comment] 2015-08-14 17:47
I've translated all scenes up to the encounter with Amaysa, plus all interface elements and NPC dialogs. So there are just the scenes from SCN6 onwards left to translate.

**Comment by trentg** [comment] 2015-08-14 17:49
Not much at all. Do you think I should wait and release 1.8 with the fixes and translation?

**Comment by akien-mga** [comment] 2015-08-14 17:50
Yeah that could be nice, I think I should be done sometime during the week-end.

**Comment by trentg** [comment] 2015-08-14 17:50
OK, I'll wait.

**Comment by akien-mga** [comment] 2015-08-14 19:48
> Any other issues?

Maybe found another one: during battles, my movement speed is often greatly reduced on some parts (when playing Egbert, I don't have the switch ability yet), as if there was something sticky on the ground. But there is no visual effect that could confirm this, so it looks more like a bug.

I can reproduce it in every combat it seems; I can send you my save if you want. I've tried with both the 1.6 release and the 1.7 translation build, same issue.

**Comment by trentg** [comment] 2015-08-14 19:49
Yeah send me your save state please.

**Comment by trentg** [comment] 2015-08-15 18:20
Is it possible to run Mageia from a USB stick/drive? I want to see if I can repeat the bug there.

**Comment by akien-mga** [comment] 2015-08-15 18:34
> Is it possible to run Mageia from a USB stick/drive? I want to see if I can repeat the bug there.

Sure, you can grab an ISO image on http://www.mageia.org/en/downloads
Take either a live CD or DVD (CD only has English, but it shouldn't be an issue for you ;)), with either GNOME3 or KDE4. I'm running KDE4 so if you want to test the exact same environment, try this one.

You can then dump it on a USB stick with dd, or any graphical tool that uses dd as a backend (but _not_ unetbootin, the ISOs are already hybrid).

**Comment by trentg** [comment] 2015-08-15 20:34
Yeah, what I actually meant was I want to be able to install a dev environment on there and other packages. So I'm downloading the install DVD now. I think I can boot from my external USB drive.

**Comment by akien-mga** [comment] 2015-08-15 20:41
Ah ok, I thought you just wanted to boot it live to test your binaries. You can also boot the install DVD from a USB drive yes.

**Comment by trentg** [comment] 2015-08-15 23:16
Sorry accidentally closed this issue.

Try something for me: does tilting your laptop cause any movement of the player? On Linux, drop sensors/motion sensors in laptops are considered joysticks. The game checks for events coming from joysticks with 0 buttons and ignores them, but maybe yours reports non-zero buttons? Also try and find which kernel module your laptop uses for motion sensing (if any.) On my Macbook it was applesmc, not sure what others there are.

**Comment by trentg** [comment] 2015-08-15 23:17
And if you find out the module, trying rmmod'ing it.

**Comment by trentg** [comment] 2015-08-16 03:17
Ok, good news. I can reproduce the issue on Mageia on my laptop, but not desktop. Bad news is it's not the drop sensor. So I'll have to dig around and figure this out, but it will be MUCH easier now that I can produce it.

**Comment by trentg** [comment] 2015-08-16 04:05
Problem does not occur in GNOME on the same Mageia install. From what I gather, the game is receiving either left/right arrow release events, or small value joystick events from somewhere.

**Comment by trentg** [comment] 2015-08-16 04:39
More info: I've compiled Allegro on Mageia and ex_keyboard_events exhibits the same issue. Pressing and holding the arrow keys produces a down event, followed by many repeat events, then an UP and another DOWN. Not sure yet if Allegro is at fault or if it's KDE, but it does work in GNOME...

**Comment by trentg** [comment] 2015-08-16 05:54
More investigating... it DOES happen on GNOME, just not as frequently. This appears to be a bug in Allegro on Linux/X11 or just in X11/something related itself.

**Comment by trentg** [comment] 2015-08-16 07:08
I've found a fix for this, in Allegro.

X11 handles key repeat events strangely by sending key up/key press events... Allegro tries to detect this, but as the X11 documentation suggests, it's not really possible. There is a function called XkbSetDetectableAutoRepeat, however, that stops the sending of the key ups events. Allegro has that function call commented out, stating that there are problems on some Xorg versions. Uncommenting it fixes this problem for me.

I'm waiting for feedback from other developers about the patch.

For curiousity, the reason it happens more on KDE is that KDE sets the key repeat rate higher than most DEs. I think if you turn key repeat off or lower, it will help the issue.

**Comment by akien-mga** [comment] 2015-08-16 09:28
> Sorry accidentally closed this issue.

Actually I was the one who closed it by writing "Fixes #5" in my commit about mkcpa-linux.sh. We've kind of hijacked the original issue to discuss a completely different bug, but that's no big deal; I'll rename the issue for clarity.

> I've found a fix for this, in Allegro.

Awesome! I guess you can already use the patch for your own binaries if you don't notice regressions, and see if it will be accepted upstream. Thanks for looking into this!

**Comment by trentg** [comment] 2015-08-16 20:36
The patch for Allegro has been committed upstream.

**Closed by trentg** 2015-08-16 20:36 UTC
Labels: bug

**Comment by akien-mga** [comment] 2015-08-16 20:38
Will you build the 1.8 binaries using your patch?

**Comment by trentg** [comment] 2015-08-16 20:39
Yes. I just build binaries but then I realized I forgot a bugfix, so I'll fix it and build them again.

**Comment by trentg** [comment] 2015-08-16 20:40
The link I sent you has the patch discussed in this thread applied, though.
